src/objects/INT_SETUP__c.object
<CustomObject>
    <description>Sets up an Salesforce Object Type for external system Integration purpose.</description>
    <fields>
        <fullName>Allowed_Schedulables__c</fullName>
        <description>In case the integration is triggerred from an Apex Schedulable, Specifies the set of Apex schedulable classes allowed for integrations.
If no value is selected, integrations will be allowed from all schedulables.
Here is an example:
CM_ETMF_Schedulable will be scheduled at specific times. There is a common Schedulable (CM_Integration_Schedulable) that is scheduled at specific times.
In case, you want to skip ETMF integration logic processed by CM_Integration_Schedulable,
you must not include CM_Integration_Schedulable for ETMF integrations for a specific Type_API_Name__c</description>
        <inlineHelpText>In case the integration is triggerred from an Apex Schedulable, Specifies the set of Apex schedulable classes allowed for integrations.
If no value is selected, integrations will be allowed from all schedulables.</inlineHelpText>
        <label>Allowed Schedulables</label>
        <picklist>
            <picklistValues>
                <fullName>CM_ETMF_Schedulable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM_CTMS_Schedulable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COM_IntegrationSchedulable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the integration configuration is enabled. Integration services will check this value before performing any integration invocations.</description>
        <inlineHelpText>Determines if the integration configuration is enabled. Integration services will check this value before performing any integration invocations.</inlineHelpText>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration System</label>
        <referenceTo>INT_SYSTEM__c</referenceTo>
        <relationshipName>Type_And_System_Integration_Setups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_API_Name__c</fullName>
        <description>API Names of the standard/custom objects</description>
        <inlineHelpText>API Names of the standard/custom objects</inlineHelpText>
        <label>Type API Name</label>
        <picklist>
            <picklistValues>
                <fullName>Apttus__APTS_Agreement__c</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Integration Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SETUP_STATUS__c.object
<CustomObject>
    <description>Maintains a record about integration status such as status, returned attributes, exceptions, etc</description>
    <fields>
        <fullName>Attributes_JSON__c</fullName>
        <description>Contains the attributes returned via the integration call.</description>
        <inlineHelpText>Contains the attributes returned via the integration call.</inlineHelpText>
        <label>Attributes JSON</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>Captures any exception occurred during the integration</description>
        <inlineHelpText>Captures any exception occurred during the integration</inlineHelpText>
        <label>Exception</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationSetup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration Setup</label>
        <referenceTo>INT_SETUP__c</referenceTo>
        <relationshipLabel>Integration Setup Statuses</relationshipLabel>
        <relationshipName>Integration_Setup_Statuses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntegrationStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration Status</label>
        <referenceTo>INT_STATUS__c</referenceTo>
        <relationshipName>Type_And_System_Integration_Statuses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Unique key used for integration. This will differ for each integration.
Ex:
ETMF_Apttus__Agreement_Document__c uses UK=Apttus__APTS_Agreement__c.Id+_+Apttus__Agreement_Document__c.Id+_+Document.Id

CTMS_Apttus__Agreement_Document__c uses
UK=Apttus__APTS_Agreement__c.Id

In case of async integrations, the async service uses this field as external id to update the appropriate row status</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key used for integration. This will differ for each integration.
In case of async integrations, the async service uses this field as external id to update the appropriate row status</inlineHelpText>
        <label>Unique Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration Setup Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Setup Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_STATUS__c.object
<CustomObject>
    <description>Defines the different integration statuses with external systems.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Determines the integration status of a object record/row.
Used in integration services to make appropriate integration invocations.
Value should not be changed once defined. Use all caps.</description>
        <inlineHelpText>Determines the integration status of a object record/row.
Used in integration services to make appropriate integration invocations.
Value should not be changed once defined. Use all caps.</inlineHelpText>
        <label>Status</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SYSTEM__c.object
<CustomObject>
    <description>Defines the different external systems used for integrations.</description>
    <fields>
        <fullName>SystemType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Type</label>
        <referenceTo>INT_SYSTEM_TYPE__c</referenceTo>
        <relationshipLabel>Integration Systems</relationshipLabel>
        <relationshipName>INT_SYSTEMS</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <description>Label of the external system. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.</description>
        <inlineHelpText>Label of the external system. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.
Examples: 
EDC_DATALABS</inlineHelpText>
        <label>System</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SYSTEM_TYPE__c.object
<CustomObject>
    <description>Defines the different external system types used for integration.</description>
    <label>Integration System Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration System Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/COM_IntegrationUtils.cls
/*

@author: Sukrut Wagh

Utility providing helper methods for sObjects related to integration framework.
Integration framework is a custom PRA framework developed to perform integrations with external
systems (mainly on-premises) in a standard & reusable fashion.

It is a lean framework consisting sObjects starting with INT_* & some common services (COM_Integration*)
that interact with these sObjects.

The idea is to administratively enable sObject types for integrations. Write 'integration services' that encapsulate the
business logic for making the external invocations. By nature, majority of the integrations are web services based & will deal with callouts.
As a practice, to align to apex's 'bulk processing' nature & get around the governer limits, 
the external web services should be designed for processing bulk records.

*/
public class COM_IntegrationUtils {
	
	private static final String SEMICOLON = ';';
	private static final String COMMA = ',';
	private COM_IntegrationUtils() {}
	private static final COM_Logger LOGGER = new COM_Logger('COM_IntegrationUtils'); 
	
	/**
	* Returns all the integration setups
	* @author	Sukrut Wagh
	* @allowed	allowed schedulables			optional. List of allowed schedulables. 
	* 											Please refer sObject-INT_SETUP__c definition for details 
	* @return	Set<INT_SETUP__c>		Returns all the integration setups
	*/
	public static Set<INT_SETUP__c> getSetups(final List<String> allowed) {
		List<INT_SETUP__c> setups = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupSelectFields(),COM_IntegrationConstants.API_INT_SETUP, 
		getIntSetupWhereClause(allowed, null, null, null), Limits.getLimitQueryRows());
		return new Set<INT_SETUP__c>(setups);
	}
	
	/**
	* Returns the integration setups
	* @author	Sukrut Wagh
	* @allowed	allowed schedulables			optional. List of allowed schedulables. 
	* 											Please refer sObject-INT_SETUP__c definition for details 	
	* @param	sysType							Integration system type	
	* @return	Set<INT_SETUP__c>		
	*/
	public static Set<INT_SETUP__c> getSetupsForSystemType(final List<String> allowed,final String sysType) {
		Set<INT_SETUP__c> resp = new Set<INT_SETUP__c>();
		if (COM_Utils.isNotEmpty(sysType)) {
			List<INT_SETUP__c> setups = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupSelectFields(),COM_IntegrationConstants.API_INT_SETUP, 
			getIntSetupWhereClause(allowed, sysType, null, null), Limits.getLimitQueryRows());
			resp = new Set<INT_SETUP__c>(setups);
		}
		return resp;
	}
	
	/**
	* Returns the integration setups
	* @author	Sukrut Wagh
	* @allowed	allowed schedulables			optional. List of allowed schedulables. 
	* 											Please refer sObject-INT_SETUP__c definition for details 	
	* @param	sys		Integration system
	* @return	Set<INT_SETUP__c>		
	*/
	public static Set<INT_SETUP__c> getSetupsForSystem(final List<String> allowed,final String sys) {
		Set<INT_SETUP__c> resp = new Set<INT_SETUP__c>();		
		if (COM_Utils.isNotEmpty(sys)) {
			List<INT_SETUP__c> setups = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupSelectFields(),COM_IntegrationConstants.API_INT_SETUP, 
			getIntSetupWhereClause(allowed, null, sys, null), Limits.getLimitQueryRows());
			resp = new Set<INT_SETUP__c>(setups);
		}
		return resp;
	}
	
	/**
	* Returns the integration setups
	* @author	Sukrut Wagh
	* @allowed	allowed schedulables			optional. List of allowed schedulables. 
	* 											Please refer sObject-INT_SETUP__c definition for details 	
	* @param	sObjType		sObject Type API name
	* @return	Set<INT_SETUP__c>		
	*/
	public static Set<INT_SETUP__c> getSetupsForSObjectType(final List<String> allowed,final String sObjType) {
		Set<INT_SETUP__c> resp = new Set<INT_SETUP__c>();
		if (COM_Utils.isNotEmpty(sObjType)) {
			List<INT_SETUP__c> setups = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupSelectFields(),COM_IntegrationConstants.API_INT_SETUP, 
			getIntSetupWhereClause(allowed, null, null, sObjType), Limits.getLimitQueryRows());
			resp = new Set<INT_SETUP__c>(setups);
		}
		return resp;
	}
	
	/**
	* Returns the integration setups
	* @author	Sukrut Wagh
	* @allowed	allowed schedulables			optional. List of allowed schedulables. 
	* 											Please refer sObject-INT_SETUP__c definition for details 	
	* @param	sObjType		sObject Type API name
	* @param	sys				Integration system
	* @return	Set<INT_SETUP__c>		
	*/
	public static INT_SETUP__c getSetupsForSObjectTypeAndSystem(final List<String> allowed,final String sObjType, final String sys) {
		INT_SETUP__c resp = null;
		if (COM_Utils.isNotEmpty(sObjType) && COM_Utils.isNotEmpty(sys)) {
			List<INT_SETUP__c> setups = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupSelectFields(),COM_IntegrationConstants.API_INT_SETUP, 
			getIntSetupWhereClause(allowed, null, sys, sObjType), 1);
			if(COM_Utils.isNotEmpty(setups)) {
				resp = setups.get(0);
			}
		}
		return resp;
	}
	
	/**
	* Returns the integration setup statuses for the given criteria
	* @author	Sukrut Wagh
	* @statuses	statuses		optional. List of valid statuses. Refer COM_IntegrationConstants.STATUS_* & sObject=INT_Status__c 
	* @param	sObjType		sObject Type API name
	* @param	sys				Integration system
	* @return	Set<INT_SETUP_STATUS__c>		
	*/
	public static Set<INT_SETUP_STATUS__c> getSetupStatuses(final List<String> statuses,final String sObjType, final String sys) {
		Set<INT_SETUP_STATUS__c> resp = new Set<INT_SETUP_STATUS__c>();
		if (COM_Utils.isNotEmpty(sObjType) && COM_Utils.isNotEmpty(sys)) {
			List<INT_SETUP_STATUS__c> intStatuses = COM_SObjectUtils.getSelectedFieldsByDynamicSOQL(getIntSetupStatusSelectFields(),
			COM_IntegrationConstants.API_INT_SETUP_STATUS, 
			getIntSetupStatusWhereClause(statuses, sys, sObjType), Limits.getLimitQueryRows());
			resp = new Set<INT_SETUP_STATUS__c>(intStatuses);
		}
		return resp;
	}
	
	/*
	*	Returns the fields to be queried for sObject=INT_SETUP__c
	*/
	private static String getIntSetupSelectFields() {
		String methodName = 'getIntSetupSelectFields';
		LOGGER.entry(methodName);
		String selectFields = 'Allowed_Schedulables__c, CreatedById, CreatedDate, IsDeleted, Enabled__c, Name, System__c,'+ 
				'LastModifiedById, LastModifiedDate, OwnerId, Id, SystemModstamp, Type_API_Name__c,'+ 
				'System__r.System__c, System__r.SystemType__r.Type__c';
		LOGGER.debug(selectFields);
		LOGGER.exit(methodName);
		return selectFields;
	}
	
	/*
	*	Creates the filter criteria for sObject=INT_SETUP__c
	*/
	private static String getIntSetupWhereClause(final List<String> allowed, final String sysType, final String sys, final String sObjType) {
		String methodName = 'getIntSetupWhereClause';
		LOGGER.entry(methodName);
		String whereClause = 'Enabled__c=true AND (allowed_schedulables__c = \'\' ';
		String allowedStr = COM_Utils.toString(allowed,SEMICOLON,null);
		if(COM_Utils.isNotEmpty(allowedStr)) {
			whereClause += 'or allowed_schedulables__c includes (\''+allowedStr+'\')';
		}
		whereClause += ')';
		
		if(COM_Utils.isNotEmpty(sysType)) {
			whereClause += ' AND System__r.SystemType__r.Type__c=\''+sysType+'\'';
		}
		if(COM_Utils.isNotEmpty(sys)) {
			whereClause += ' AND System__r.System__c= \''+sys+'\'';
		}
		if(COM_Utils.isNotEmpty(sObjType)) {
			whereClause += ' AND Type_API_Name__c=\''+sObjType+'\'';
		}
		LOGGER.debug(whereClause);
		LOGGER.exit(methodName);
		return whereClause;
	}
	
	/*
	*	Returns the fields to be queried for sObject=INT_SETUP_STATUS__c
	*/
	public static String getIntSetupStatusSelectFields() {
		String methodName = 'getIntSetupStatusSelectFields';
		LOGGER.entry(methodName);
		String selectFields = 'Attributes_JSON__c, CreatedById, CreatedDate, IsDeleted, Exception__c, IntegrationStatus__c, LastModifiedById, LastModifiedDate, OwnerId, Id,'+ 
				'SystemModstamp, IntegrationSetup__c, Name, Unique_Key__c, '+ 
				'IntegrationStatus__r.Status__c, IntegrationSetup__r.Type_API_Name__c, IntegrationSetup__r.System__r.System__c';
		LOGGER.debug(selectFields);
		LOGGER.exit(methodName);
		return selectFields;
	}
	
	/*
	*	Creates the filter criteria for sObject=INT_SETUP_STATUS__c
	*/
	private static String getIntSetupStatusWhereClause(final List<String> statuses, final String sys, final String sObjType) {
		String methodName = 'getIntSetupStatusWhereClause';
		LOGGER.entry(methodName);
		String whereClause = '';
		String andStr = ' AND ';
		String statusesStr = COM_Utils.toString(statuses,COMMA,'\'');
		if(COM_Utils.isNotEmpty(statusesStr)) {
			whereClause += 'IntegrationStatus__r.Status__c IN ('+statusesStr+')';
		}
		if(COM_Utils.isNotEmpty(sys)) {
			whereClause += andStr+' IntegrationSetup__r.System__r.System__c = \''+sys+'\'';
		}
		if(COM_Utils.isNotEmpty(sObjType)) {
			whereClause += andStr+' IntegrationSetup__r.Type_API_Name__c=\''+sObjType+'\'';
		}
		if(COM_Utils.isNotEmpty(whereClause) && whereClause.startsWithIgnoreCase(andStr)) {
			whereClause = whereClause.removeStartIgnoreCase(andStr);
		}
		LOGGER.debug(whereClause);
		LOGGER.exit(methodName);
		return whereClause;
	}
	
}