src/objects/INT_SETUP__c.object
<CustomObject>
    <description>Sets up an Salesforce Object Type for external system Integration purpose.</description>
    <fields>
        <fullName>Allowed_Schedulables__c</fullName>
        <description>In case the integration is triggerred from an Apex Schedulable, Specifies the set of Apex schedulable classes allowed for integrations.
If no value is selected, integrations will be allowed from all schedulables.
Here is an example:
CM_ETMF_Schedulable will be scheduled at specific times. There is a common Schedulable (CM_Integration_Schedulable) that is scheduled at specific times.
In case, you want to skip ETMF integration logic processed by CM_Integration_Schedulable,
you must not include CM_Integration_Schedulable for ETMF integrations for a specific Type_API_Name__c</description>
        <inlineHelpText>In case the integration is triggerred from an Apex Schedulable, Specifies the set of Apex schedulable classes allowed for integrations.
If no value is selected, integrations will be allowed from all schedulables.</inlineHelpText>
        <label>Allowed Schedulables</label>
        <picklist>
            <picklistValues>
                <fullName>CM_ETMF_Schedulable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM_CTMS_Schedulable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COM_IntegrationSchedulable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the integration configuration is enabled. Integration services will check this value before performing any integration invocations.</description>
        <inlineHelpText>Determines if the integration configuration is enabled. Integration services will check this value before performing any integration invocations.</inlineHelpText>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration System</label>
        <referenceTo>INT_SYSTEM__c</referenceTo>
        <relationshipName>Type_And_System_Integration_Setups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_API_Name__c</fullName>
        <description>API Names of the standard/custom objects</description>
        <inlineHelpText>API Names of the standard/custom objects</inlineHelpText>
        <label>Type API Name</label>
        <picklist>
            <picklistValues>
                <fullName>Apttus__APTS_Agreement__c</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Integration Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SETUP_STATUS__c.object
<CustomObject>
    <description>Maintains a record about integration status such as status, returned attributes, exceptions, etc</description>
    <fields>
        <fullName>Attributes_JSON__c</fullName>
        <description>Contains the attributes returned via the integration call.</description>
        <inlineHelpText>Contains the attributes returned via the integration call.</inlineHelpText>
        <label>Attributes JSON</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>Captures any exception occurred during the integration</description>
        <inlineHelpText>Captures any exception occurred during the integration</inlineHelpText>
        <label>Exception</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationSetup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration Setup</label>
        <referenceTo>INT_SETUP__c</referenceTo>
        <relationshipLabel>Integration Setup Statuses</relationshipLabel>
        <relationshipName>Integration_Setup_Statuses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntegrationStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration Status</label>
        <referenceTo>INT_STATUS__c</referenceTo>
        <relationshipName>Type_And_System_Integration_Statuses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Unique key used for integration. This will differ for each integration.
Ex:
ETMF_Apttus__Agreement_Document__c uses UK=Apttus__APTS_Agreement__c.Id+_+Apttus__Agreement_Document__c.Id+_+Document.Id

CTMS_Apttus__Agreement_Document__c uses
UK=Apttus__APTS_Agreement__c.Id

In case of async integrations, the async service uses this field as external id to update the appropriate row status</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key used for integration. This will differ for each integration.
In case of async integrations, the async service uses this field as external id to update the appropriate row status</inlineHelpText>
        <label>Unique Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration Setup Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Setup Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_STATUS__c.object
<CustomObject>
    <description>Defines the different integration statuses with external systems.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description about the status.
Ex: What it means &amp; how it is used in integration services.</description>
        <inlineHelpText>Brief description about the status.
Ex: What it means &amp; how it is used in integration services.</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Determines the integration status of a object record/row.
Used in integration services to make appropriate integration invocations.
Value should not be changed once defined. Use all caps.</description>
        <inlineHelpText>Determines the integration status of a object record/row.
Used in integration services to make appropriate integration invocations.
Value should not be changed once defined. Use all caps.</inlineHelpText>
        <label>Status</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SYSTEM__c.object
<CustomObject>
    <description>Defines the different external systems used for integrations.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description about the system.
Example:
CTMS or Clinical Trials Management System is an application based on Oracle Siebel Systems e-Clinical software.  It is the central, global repository for clinical trial monitoring and management at PRA.</description>
        <inlineHelpText>Brief description about the system.
Example:
CTMS or Clinical Trials Management System is an application based on Oracle Siebel Systems e-Clinical software.  It is the central, global repository for clinical trial monitoring and management at PRA.</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SystemType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Type</label>
        <referenceTo>INT_SYSTEM_TYPE__c</referenceTo>
        <relationshipLabel>Integration Systems</relationshipLabel>
        <relationshipName>INT_SYSTEMS</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <description>Label of the external system. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.</description>
        <inlineHelpText>Label of the external system. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.
Examples: 
EDC_DATALABS</inlineHelpText>
        <label>System</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_SYSTEM_TYPE__c.object
<CustomObject>
    <description>Defines the different external system types used for integration.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description about the System type.</description>
        <inlineHelpText>Brief description about the System type.
Example:
CTMS: http://en.wikipedia.org/wiki/Clinical_trial_management_system
ETMF: http://en.wikipedia.org/wiki/Electronic_trial_master_file
SAFETY: http://en.wikipedia.org/wiki/Pharmacovigilance</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Label of the external system types. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.
Examples: 
ETMF
EDC
SAFETY
CTMS</description>
        <inlineHelpText>Label of the external system types. Used in business logic by integration services. Once a record is created, this value should never be changed.
Please create these labels following some standard conventions. Use upper case only.
Examples: 
ETMF
EDC</inlineHelpText>
        <label>Type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration System Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration System Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/COM_IntegrationUtilsUTest.cls
@isTest
public with sharing class COM_IntegrationUtilsUTest {
	
	static testMethod void getSetupsTest_Empty (){
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(new List<String>{'Unauthorized_Schedulable 1','Unauthorized_Schedulable 2'});
		system.assertEquals(0, setups.size(), 'Integration Setups found when no data exists!');
	}
	
	static testMethod void getSetupsTest (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		Test.startTest();
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(new List<String>{setup.Allowed_Schedulables__c});
		Test.stopTest();
		system.assertEquals(1, setups.size(), 'Integration Setups not found!');
		for(INT_SETUP__c retSetup: setups) {
			system.assertEquals(setup.Id, retSetup.Id, 'Integration Setup - Id do not match!');
			system.assertEquals(sys.Id, retSetup.System__c , 'Integration Setup - System do not match!');
			break;
		}
	}
	
	static testMethod void getSetupsForSystemTest_Empty (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(allowed);
		system.assertEquals(1, setups.size(), 'No Integration Setups found!');
		Test.startTest();
		setups = COM_IntegrationUtils.getSetupsForSystem(allowed,'System X');
		Test.stopTest();
		system.assertEquals(0, setups.size(), 'Integration Setups found for non-existent system!');
	}
	
	static testMethod void getSetupsForSystemTest (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Test.startTest();
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetupsForSystem(allowed,sys.System__c);
		Test.stopTest();
		system.assertEquals(1, setups.size(), 'Integration Setups not found!');
		for(INT_SETUP__c retSetup: setups) {
			system.assertEquals(setup.Id, retSetup.Id, 'Integration Setup - Id do not match!');
			system.assertEquals(sys.Id, retSetup.System__c , 'Integration Setup - System do not match!');
			break;
		}
	}
	
	static testMethod void getSetupsForSObjectTypeTest_Empty (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(allowed);
		system.assertEquals(1, setups.size(), 'No Integration Setups found!');
		Test.startTest();
		setups = COM_IntegrationUtils.getSetupsForSObjectType(allowed,'Type_X__c');
		Test.stopTest();
		system.assertEquals(0, setups.size(), 'Integration Setups found for non-existent sObject type!');
	}
	
	static testMethod void getSetupsForSObjectTypeTest (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Test.startTest();
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetupsForSObjectType(allowed,setup.Type_API_Name__c);
		Test.stopTest();
		system.assertEquals(1, setups.size(), 'Integration Setups not found!');
		for(INT_SETUP__c retSetup: setups) {
			system.assertEquals(setup.Id, retSetup.Id, 'Integration Setup - Id do not match!');
			system.assertEquals(sys.Id, retSetup.System__c , 'Integration Setup - System do not match!');
			system.assertEquals(setup.Type_API_Name__c, retSetup.Type_API_Name__c , 'Integration Setup - sObject type do not match!');
			break;
		}
	}
	
	static testMethod void getSetupsForSystemTypeTest_Empty (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(allowed);
		system.assertEquals(1, setups.size(), 'No Integration Setups found!');
		Test.startTest();
		setups = COM_IntegrationUtils.getSetupsForSystemType(allowed,'SYS_TYPE_X');
		Test.stopTest();
		system.assertEquals(0, setups.size(), 'Integration Setups found for non-existent System type!');
	}
	
	static testMethod void getSetupsForSystemTypeTest (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Test.startTest();
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetupsForSystemType(allowed,sysType.Type__c);
		Test.stopTest();
		system.assertEquals(1, setups.size(), 'Integration Setups not found!');
		for(INT_SETUP__c retSetup: setups) {
			system.assertEquals(setup.Id, retSetup.Id, 'Integration Setup - Id do not match!');
			system.assertEquals(sys.Id, retSetup.System__c , 'Integration Setup - System do not match!');
			system.assertEquals(sysType.Type__c, retSetup.System__r.SystemType__r.Type__c , 'Integration Setup - system type do not match!');
			break;
		}
	}
	
	static testMethod void getSetupsForSObjectTypeAndSystemTest_Empty (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Set<INT_SETUP__c> setups = COM_IntegrationUtils.getSetups(allowed);
		system.assertEquals(1, setups.size(), 'No Integration Setups found!');
		Test.startTest();
		INT_SETUP__c retSetup = COM_IntegrationUtils.getSetupsForSObjectTypeAndSystem(allowed,setup.Type_API_Name__c,'SYS_TYPE_X');
		system.assertEquals(null, retSetup, 'Integration Setup found for non-existent System type!');
		
		retSetup = COM_IntegrationUtils.getSetupsForSObjectTypeAndSystem(allowed,'Type_X__c',sys.System__c);
		system.assertEquals(null, retSetup, 'Integration Setup found for non-existent sObject type!');
		Test.stopTest();
	}
	
	static testMethod void getSetupsForSObjectTypeAndSystemTest (){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<String> allowed = new List<String>{setup.Allowed_Schedulables__c};
		Test.startTest();
		INT_SETUP__c retSetup = COM_IntegrationUtils.getSetupsForSObjectTypeAndSystem(allowed,setup.Type_API_Name__c,sys.System__c);
		Test.stopTest();
		system.assertNotEquals(null, retSetup, 'Integration Setup not found!');
		system.assertEquals(setup.Id, retSetup.Id, 'Integration Setup - Id do not match!');
		system.assertEquals(setup.Type_API_Name__c, retSetup.Type_API_Name__c, 'Integration Setup - Type_API_Name__c do not match!');
		system.assertEquals(sys.Id, retSetup.System__c , 'Integration Setup - System do not match!');
		system.assertEquals(sysType.Type__c, retSetup.System__r.SystemType__r.Type__c , 'Integration Setup - system type do not match!');
	}
	
	static testMethod void getSetupStatusesTest_Empty(){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<INT_STATUS__c> statuses = getIntStatuses(4);
		insert statuses;
		Test.startTest();
		
		//No integration status filter
		Set<INT_SETUP_STATUS__c> retSetupStatusesNoIntStatusFilter = COM_IntegrationUtils.getSetupStatuses(null,
									 setup.Type_API_Name__c,sys.System__c);
		
		List<INT_SETUP_STATUS__c> setupStatuses = getSetupStatuses(6, setup, statuses);
		insert setupStatuses;
		
		//Filter by a invalid integration status
		Set<INT_SETUP_STATUS__c> retSetupStatusesFilterOneIntStatus = 
									COM_IntegrationUtils.getSetupStatuses(new List<String>{'Invalid status'},
									 setup.Type_API_Name__c,sys.System__c);
		//Pass all integration status for filter											
		Set<INT_SETUP_STATUS__c> retSetupStatusesAllIntStatus = COM_IntegrationUtils.getSetupStatuses(getIntStatusesString(statuses),
									 setup.Type_API_Name__c,sys.System__c);									 
		Test.stopTest();
		system.assertEquals(0, retSetupStatusesNoIntStatusFilter.size());
		system.assertEquals(0, retSetupStatusesFilterOneIntStatus.size());
		system.assertNotEquals(null, retSetupStatusesAllIntStatus);
		system.assertEquals(6, retSetupStatusesAllIntStatus.size());
		
	}
	
	static testMethod void getSetupStatusesTest(){
		INT_SYSTEM_TYPE__c sysType = getSystemTypes(1).get(0);
		insert sysType;
		INT_SYSTEM__c sys = getSystems(1, sysType).get(0);
		insert sys;
		INT_SETUP__c setup = getSystemSetups(1, sys).get(0);
		insert setup;
		List<INT_STATUS__c> statuses = getIntStatuses(4);
		insert statuses;
		List<INT_SETUP_STATUS__c> setupStatuses = getSetupStatuses(6, setup, statuses);
		insert setupStatuses;
		Test.startTest();
		//Filter by a integration status
		Set<INT_SETUP_STATUS__c> retSetupStatusesFilterOneIntStatus = 
									COM_IntegrationUtils.getSetupStatuses(new List<String>{statuses.get(0).Status__c},
									 setup.Type_API_Name__c,sys.System__c);
		//No integration status filter
		Set<INT_SETUP_STATUS__c> retSetupStatusesNoIntStatusFilter = COM_IntegrationUtils.getSetupStatuses(null,
									 setup.Type_API_Name__c,sys.System__c);
		//Pass all integration status for filter											
		Set<INT_SETUP_STATUS__c> retSetupStatusesAllIntStatus = COM_IntegrationUtils.getSetupStatuses(getIntStatusesString(statuses),
									 setup.Type_API_Name__c,sys.System__c);
		Test.stopTest();
		system.assertNotEquals(null, retSetupStatusesFilterOneIntStatus);
		system.assertNotEquals(null, retSetupStatusesNoIntStatusFilter);
		system.assertNotEquals(null, retSetupStatusesAllIntStatus);
		
		system.assertEquals(1, retSetupStatusesFilterOneIntStatus.size());
		system.assertEquals(6, retSetupStatusesNoIntStatusFilter.size());
		system.assertEquals(6, retSetupStatusesAllIntStatus.size());
		
	}
	
	/*************************** Boilerplate helper methods  ****************************/
	
	private static List<INT_SYSTEM_TYPE__c> getSystemTypes(Integer size) {
		List<INT_SYSTEM_TYPE__c> types = new List<INT_SYSTEM_TYPE__c>();
		INT_SYSTEM_TYPE__c sysType = null; 
		for(Integer i=0;i<size;i++) {
			sysType = new INT_SYSTEM_TYPE__c(Type__c='SYS TYPE-'+i, Description__c='DESC-'+i);
			sysType.Name = sysType.Type__c;
			types.add(sysType);
		}
		return types;
	}
	
	private static List<INT_STATUS__c> getIntStatuses(Integer size) {
		List<INT_STATUS__c> statuses = new List<INT_STATUS__c>();
		INT_STATUS__c status = null; 
		for(Integer i=0;i<size;i++) {
			status = new INT_STATUS__c(Status__c='STATUS-'+i, Description__c='DESC-'+i);
			status.Name = status.Status__c;
			statuses.add(status);
		}
		return statuses;
	}
	
	private static List<String> getIntStatusesString(final List<INT_STATUS__c> statuses) {
		List<String> statusesStr = new List<String>();
		if(COM_Utils.isNotEmpty(statuses)) {
			for(INT_STATUS__c status: statuses) {
				statusesStr.add(status.Status__c);
			}
		}
		return statusesStr;
	}
	
	private static List<INT_SYSTEM__c> getSystems(Integer size, final INT_SYSTEM_TYPE__c sysType) {
		List<INT_SYSTEM__c> systems = new List<INT_SYSTEM__c>();
		if(null != sysType) {
			INT_SYSTEM__c sys = null; 
			for(Integer i=0;i<size;i++) {
				sys = new INT_SYSTEM__c(System__c='SYS-'+i, Description__c='DESC-'+i, SystemType__c=sysType.Id);
				sys.Name = sys.System__c;
				systems.add(sys);
			}
		}
		return systems;
	}
	
	private static List<INT_SETUP__c> getSystemSetups(Integer size, final INT_SYSTEM__c sys) {
		List<INT_SETUP__c> setups = new List<INT_SETUP__c>();
		if(null != sys) {
			INT_SETUP__c setup = null; 
			for(Integer i=0;i<size;i++) {
				setup = new INT_SETUP__c(Enabled__c=true,Allowed_Schedulables__c='Sched-'+i,Type_API_Name__c='API TYPE-'+i,System__c=sys.Id);
				setup.Name = sys.Name + '-' + setup.Type_API_Name__c;
				setups.add(setup);
			}
		}
		return setups;
	}
	
	private static List<INT_SETUP_STATUS__c> getSetupStatuses(Integer size, final INT_SETUP__c setup, final List<INT_STATUS__c> statuses) {
		List<INT_SETUP_STATUS__c> setupStatuses = new List<INT_SETUP_STATUS__c>();
		if(null != setup && COM_Utils.isNotEmpty(statuses)) {
			INT_SETUP_STATUS__c setupStatus = null;
			INT_STATUS__c status = statuses.get(0);
			for(Integer i=0;i<size;i++) {
				if(i < statuses.size()) {
					status = statuses.get(i);
				}
				setupStatus = new INT_SETUP_STATUS__c(Attributes_JSON__c='JSON data-'+i, Exception__c='', IntegrationSetup__c=setup.Id,
													 IntegrationStatus__c=status.Id, Unique_Key__c='UK-'+i);
				setupStatus.Name = status.Name +'-'+setupStatus.Unique_Key__c;										 
				setupStatuses.add(setupStatus);
			}
		}
		return setupStatuses;
	}
	
}